nuevaEra/apps/core/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = patterns('',
    url(r'^$', 'core.views.home', name='core_home'),
    url(r'^registrar/', 'core.views.registrar', name='core_registrar'),
    url(r'^error/', 'core.views.error', name='core_error'),
    url(r'^loguearse/', 'core.views.loguearse', name='core_loguearse'),
    url(r'^desloguearse/', 'core.views.desloguearse', name='core_desloguearse'),
)

nuevaEra/apps/musica/urls.py
from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('musica.views',
    url(r'^$', 'index', name="musica_index"),
    url(r'^(?P<tema_id>\d+)/$', 'detalle', name="musica_detalle"),
)

nuevaEra/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       
    url(r'^', include('core.urls')),
    url(r'^musica/', include('musica.urls')),
    # Examples:
    # url(r'^$', 'nuevaEra.views.home', name='home'),
    # url(r'^nuevaEra/', include('nuevaEra.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            }),
    )

nuevaEra/apps/core/models.py
from django.db import models

# Create your models here.

nuevaEra/apps/musica/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Artista(models.Model):
    nombre = models.CharField(blank=False, max_length=100)
    
    def __unicode__(self):
        return self.nombre

class Tema(models.Model):
    usuario = models.ForeignKey(User)
    artista = models.ForeignKey(Artista)
    titulo = models.CharField(blank=False, max_length=100) 
    datetime = models.DateTimeField(blank=True, auto_now_add=True)
    audio = models.FileField(upload_to="temas", null=True, blank=True)
    
    def __unicode__(self):
        return self.titulo

class Comentario(models.Model):
    usuario = models.ForeignKey(User)
    tema = models.ForeignKey(Tema)
    contenido = models.TextField(blank=False, max_length=500)
    
    def __unicode__(self):
        return self.contenido

nuevaEra/apps/core/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _

class UserForm(forms.Form):
    
    username = forms.CharField(label=_("Usuario"), required=True)
    password = forms.CharField(label=_("Password"), widget=forms.PasswordInput, max_length=20, min_length=5, required=True)
    password2 = forms.CharField(label=_("Confirmar password"), widget=forms.PasswordInput, max_length=20, min_length=5, required=True)
    email = forms.EmailField(label=_("Email"), required=True)
    
    def save(self):
        user = User(
            email = self.cleaned_data["email"],
            username = self.cleaned_data["username"]
        )
        user.set_password(self.cleaned_data["password"])
        user.save()
    
    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        password2 = cleaned_data.get("password2")
        #!! check for equal and not none

        if password != password2:
            self._errors["password"]=self.error_class([_(u"Passwords must match.")])
            self._errors["password2"]=self.error_class([_(u"Passwords must match.")])

        return cleaned_data

nuevaEra/apps/musica/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from musica.models import Comentario
from django.forms.widgets import Textarea

class ComentarioForm(forms.Form):
    contenido = forms.CharField(required=True, 
                                help_text=_("Maximo 500 caracteres"),
                                label=_("Comentario"),
                                 widget=forms.Textarea(attrs={'cols': 100, 'rows': 15}))
    
    class Meta:
        model = Comentario
        fields = ('contenido')
        
    def save(self, theme, user):
        comentario = Comentario(
                                contenido = self.cleaned_data['contenido'],
                                usuario = user,
                                tema = theme
                                )
        comentario.save()

nuevaEra/apps/core/views.py
# Create your views here.
from django.shortcuts import render_to_response, render, redirect
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.template.context import RequestContext
from core.forms import UserForm
from django.contrib.auth import authenticate, login, logout

def home(request):
    return render(request, "core/home.html")

def registrar(request):
    if request.user.is_authenticated():
        return redirect("core_home")
    form = UserForm()
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect("core_home")
    return render(request, "core/registrar.html", {'form': form })


def loguearse(request):
    username = request.POST['username']
    password = request.POST['password']
    print request.POST
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            # Redirect to a success page.
            return redirect("core_home")
        else:
            # Return a 'disabled account' error message
            return error(request, "La cuenta esta deshabilitada")
    else:
        # Return an 'invalid login' error message.
        return error(request, "La cuenta es invalida")

    
def error(request, mensaje):
    return render(request, "core/error.html", { 'msj' : mensaje })

def desloguearse(request):
    logout(request)
    return redirect("core_home")

nuevaEra/apps/musica/views.py
from django.shortcuts import render_to_response, render, redirect
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.template.context import RequestContext
from django.contrib.auth import authenticate, login, logout
from musica.models import Artista, Tema
from musica.forms import ComentarioForm

def index(request):
    temas = Tema.objects.all()
    return render(request, "musica/index.html", {'temas' : temas})
    
def detalle(request, tema_id):
    #pedir el tema filtrando con el id y despues pasar los datos al template
    tema = Tema.objects.filter(pk=tema_id)[0]
    
    #manejo del formulario del comentario
    if request.user.is_authenticated():        
        if request.method == "POST":
            form = ComentarioForm(request.POST)
            if form.is_valid():
                comentario = form.save(tema, request.user)
                return redirect("musica_detalle", tema_id)
        else:
            form = ComentarioForm()
        return render(request, "musica/detalle.html", {'tema' : tema, 'form': form })
    return render(request, "musica/detalle.html", {'tema' : tema})
    
    return render(request, "musica/detalle.html", {'tema': tema, 'form' : form })

    

nuevaEra/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}Este es el base{% endblock %}</title>

	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/style.css" />	
	<link href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/dewplayer_styles.css" />
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="{% url core_home %}">Nueva Era</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li><a href="{% url core_home %}">Home</a></li>
              <li><a href="{% url musica_index %}">Musica</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Opciones <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li class="nav-header">Acerca de nosotros</li>
                  <li><a href="#">Quienes somos</a></li>
                  <li class="divider"></li>
                  <li class="nav-header">Contacto</li>
                  <li><a href="mailto:nuevaEra@gmail.com?Subject=Asunto">Mandanos un Email</a></li>
                </ul>
              </li>              
            </ul>
            {% if user.is_authenticated %}            	 
					<form class="navbar-form pull-right" method="post" action="{% url core_desloguearse %} ">{% csrf_token %}
						<button type="submit" class="btn">Cerrar sesion</button>
					</form>
					<p class="nav-header" id="bienvenido">Bienvenido {{ user.username }} !</p>
					{% if user.is_staff %}
						<a href="/admin/" class="nav-header" id="admin_link">Administracion</a>
					{% endif %}
				{% else %} 	
            	<form class="navbar-form pull-right" method="post" action=" {% url core_loguearse %} ">{% csrf_token %}
              		<input class="span2" type="text" name="username" placeholder="User">
              		<input class="span2" type="password" name="password" placeholder="Password">
              		<button type="submit" class="btn">Loguearse</button>
            	</form>
            	<ul class="nav pull-right"><li><a href="{% url core_registrar %}">Registrarse</a></li></ul>
            {% endif %}
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    
	<div class="container separador">
		<div class="row header">
  			<div class="span4 logo">
  				<img src="{{ STATIC_URL }}css/imagenes/nuevaEra.jpg" alt="Logo" >
  			</div>
  			<div class="span2"></div>
		</div>
		<div class="row menu_lateral">
			<div class="span2">
				<ul>
					<li><a href="{% url core_home %}" >Home</a></li>
					<li><a href="{% url musica_index %}" >Musica</a></li>
					<li><a href="#" >Link</a></li>
					<li><a href="#" >Link</a></li>
					<li><a href="#" >Link</a></li>					
				</ul>
			</div>
			<div class="span10">
				{% block content %}
					This is the default content!				
   			{% endblock %}
			</div>
		</div>		
	</div>
	<!-- Footer -->
	<div class="nav navbar-inverse navbar-bottom footer">
		<div class="row white">
			<div class="span2 pull-left center">
				<img src="{{ STATIC_URL }}css/imagenes/guitarra_v.jpg" alt="guitarra roja izquierda" height="150" width="50">
			</div>
			<div class="span3" id="carrusel_centrado">
				<div id="myCarousel" class="carousel slide">
			  		<!-- Carousel items -->
			  		<div class="carousel-inner">
			    		<div class="active item">
			    			<img src="{{ STATIC_URL }}css/imagenes/guitarra_roja_l.jpg" alt="guitarra roja izquierda" class="imagenes_carrusel">
			    		</div>
			    		<div class="item">
			    			<img src="{{ STATIC_URL }}css/imagenes/guitarra_roja_r.jpg" alt="guitarra roja derecha" class="imagenes_carrusel">
			    		</div>
			  		</div>
			  		<!-- Carousel nav -->
			  		<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
			  		<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
				</div>
			</div>		
			<div class="span2 pull-right center">
				<img src="{{ STATIC_URL }}css/imagenes/guitarra_v.jpg" alt="guitarra roja derecha" height="150" width="50">
			</div>
		</div>
	</div>
	
	<!--javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{ STATIC_URL }}js/jquery.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-transition.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-alert.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-modal.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-dropdown.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-scrollspy.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-tab.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-tooltip.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-popover.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-button.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-collapse.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-carousel.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-typeahead.js"></script>
   <!-- <script type="text/javascript" src="http://webplayer.yahooapis.com/player.js"></script> -->
    <script type="text/javascript" src="{{ STATIC_URL }}js/yahooWebPlayer.js"></script>
</body>
</html>

nuevaEra/templates/core/error.html
{% extends 'base.html' %}
{% block title %}Pagina de error{% endblock %}
{% block content %}
	{{ mensaje }}
{% endblock %}

nuevaEra/templates/core/home.html
{% extends 'base.html' %}
{% block title %}Nueva Era{% endblock %}
{% block content %}

	{% if user.is_authenticated %} 
		Bienvenido {{ user }} ! 
	{% else %} 
		Logueate. 
	{% endif %}
	

{% endblock %}

nuevaEra/templates/core/registrar.html
{% extends 'base.html' %}
{% block title %}Pagina de registro{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
	
	<div>
		Formulario de Registro
		<form class="bootstrap" method="post" action=".">{% csrf_token %}
			{{ form|crispy }}
			<input type="submit" value="Registrar" />
		</form>
	</div>

{% endblock %}

nuevaEra/templates/musica/detalle.html
{% extends 'base.html' %}
{% block title %}{{ tema.artista }}: {{ tema.titulo }}{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
	
	<table class="table">					
    	<tr>
    		<th>Titulo</th><th>Artista</th>      		
    	</tr>
    	<tr>
    		<td>{{ tema.titulo }}</td><td>{{ tema.artista }}</td>
    	</tr>
   </table>
   <audio controls="controls">
		<source src="{{ MEDIA_URL }}{{ tema.audio }}" type="audio/mp3" />		
	</audio>
		
	<object type="application/x-shockwave-flash" data="{{ STATIC_URL }}dewplayer-vol.swf" width="240" height="20" id="dewplayer-vol">
		<param name="movie" value="{{ STATIC_URL }}dewplayer-vol.swf" />
		<param name="flashvars" value="mp3={{ MEDIA_URL }}{{ tema.audio }}" />
		<param name="wmode" value="transparent" />
	</object>
	
	<a href="{{ MEDIA_URL }}{{ tema.audio }}">Play</a>
	
	<h3>Comentarios</h3>		
	
	{% if user.is_authenticated %}
		<div>
			<h3>Comenta el tema</h3>
			<form class="bootstrap" method="post" action=".">{% csrf_token %}
				{{ form|crispy }}
				<input type="submit" value="Enviar comentario" />
			</form>
		</div>	
	{% endif %}
	
	<table class="table table-bordered">
		{% for comentario in tema.comentario_set.all %}					
    		<tr>
    			<th class="comentario">Usuario: {{ comentario.usuario }}</th>
    		</tr>		
			<tr>
    			<th>Comento:</th>
    		</tr>		
			<tr>
				<td>{{ comentario.contenido }}</td>
			</tr>
		{% endfor %}
	</table>
	
{% endblock %}

nuevaEra/templates/musica/index.html
{% extends 'base.html' %}
{% block title %}Musica{% endblock %}
{% block content %}
{% endblock %}